### ISSUE TITLE
Use http.MaxBytesReader instead of io.LimitReader

### ISSUE THREAD

**Issue by akshayjshah** [rerpc/rerpc#3]
We should implement the `MaxReadBytes` option with `http.MaxBytesReader` instead of the plain `io.LimitReader` - that's what it's for!

**Comment by severb** [comment]
I can take a stab at this if you're not in a hurry to land it.

**Comment by akshayjshah** [comment]
Sever! It's good to hear from you, though I'm surprised you discovered my side hack :)

I've got a bunch of local commits piled up that may obsolete this issue, so hold off a bit. If you're interested in helping out, though, I'll make more of an effort to create issues for potential fixes & improvements.

**Comment by severb** [comment]
I'm looking for a side project and this caught my attention. I like the idea and I'd love to help out. I think I can put a few hours a week into it.

**Comment by akshayjshah** [comment]
Turns out that this logic is now being handled further away from the HTTP layer, so this isn't a good idea. I think we'd also prefer to impose these limits on a per-message basis rather than for the whole stream, so we probably don't want to slap a limit on the whole request body.
